import 'dart:async';
import 'dart:convert';
import 'dart:developer';
import 'dart:math';

import 'package:another_flushbar/flushbar.dart';
import 'package:custom_radio_grouped_button/CustomButtons/ButtonTextStyle.dart';
import 'package:custom_radio_grouped_button/CustomButtons/CustomCheckBoxGroup.dart';
import 'package:custom_radio_grouped_button/CustomButtons/CustomRadioButton.dart';
import 'package:expandable/expandable.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:ios_edunitas/constant/constant.dart';
import 'package:ios_edunitas/model/Auth/LoginModel.dart';
import 'package:ios_edunitas/model/Auth/UsersDetailModel.dart';
import 'package:ios_edunitas/model/Campus/AngsuranSpb.dart';
import 'package:ios_edunitas/model/Campus/listdetail_jurusan_pengelompok.dart';
import 'package:ios_edunitas/model/Campus/AngsuranSpbAngsuran.dart';
import 'package:ios_edunitas/model/Campus/check_search_prodi.dart';
import 'package:ios_edunitas/model/Master/CampusKelas.dart';
import 'package:ios_edunitas/model/Master/KelasModel.dart';
import 'package:ios_edunitas/model/Campus/ListCampus.dart';
import 'package:ios_edunitas/model/Master/LogoGambar.dart';

import 'package:ios_edunitas/model/Master/MasterDaerahModel.dart';
import 'package:ios_edunitas/model/Master/MasterJurusanModel.dart';
import 'package:ios_edunitas/model/Campus/PhotoModel.dart';
import 'package:ios_edunitas/model/Campus/SipemaModel.dart';
import 'package:ios_edunitas/model/Master/MetodePembayaranModel.dart';
import 'package:ios_edunitas/model/Master/PendidikanModel.dart';
import 'package:ios_edunitas/model/Master/SearchProdiModel.dart';
import 'package:ios_edunitas/model/Master/SmbModel.dart';
import 'package:ios_edunitas/model/Master/StatusModel.dart';
import 'package:ios_edunitas/model/Master/UnitAreaModel.dart';
import 'package:ios_edunitas/model/educampus/listedu.dart';
import 'package:ios_edunitas/model/transaction/transactionModel2.dart';
import 'package:ios_edunitas/pages/Account/me/me_partner/me_partner.dart';
import 'package:ios_edunitas/pages/Auth/Auth.dart';
import 'package:ios_edunitas/pages/Home/home.dart';
import 'package:ios_edunitas/pages/Home/karir/karir.dart';
import 'package:ios_edunitas/pages/Home/widget_home/partner/partner.dart';
import 'package:ios_edunitas/pages/Home/widget_home/profil_video.dart';
import 'package:ios_edunitas/pages/Inbox/inbox.dart';
import 'package:ios_edunitas/pages/Transaction/transaction.dart';
import 'package:ios_edunitas/pages/Home/widget_home/agensi/widget_agensi.dart';
import 'package:ios_edunitas/pages/Home/pendaftaran_online/pendaftaran_online.dart';
import 'package:ios_edunitas/pages/Home/widget_home/promosi/widget_promosi.dart';
import 'package:ios_edunitas/pages/Home/widget_home/donasi/widget_donasi.dart';
import 'package:ios_edunitas/shared/shared.dart';
import 'package:ios_edunitas/viewmodels/UserViewModel.dart';
import 'package:ios_edunitas/viewmodels/eduinfoview_model.dart';
import 'package:ios_edunitas/viewmodels/viewmodel.dart';
import 'package:ios_edunitas/viewmodels/whitlistview_model.dart';
import 'package:ios_edunitas/widget/widget.dart';
import 'package:flutter_html/flutter_html.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:get/get.dart';

import 'package:connectivity/connectivity.dart';
import 'package:html/dom.dart' as dom;
import 'package:html/parser.dart';

import 'package:http/http.dart' as http;
import 'dart:async';
import 'dart:core';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:intl/intl.dart';
import 'package:url_launcher/url_launcher.dart';

// import 'package:youtube_player_flutter/youtube_player_flutter.dart';

import 'package:shimmer/shimmer.dart';
import 'package:flutter_share/flutter_share.dart';

part 'MenuHome.dart';
part 'Menu_Berita.dart';
part 'menu_promosi.dart';
part 'PageKampus.dart';
part 'MenuRekomendasi.dart';
part 'ListKampusCard.dart';
part 'metodepambayaran.dart';

part 'profil_video_youtube.dart';
part 'SearchKampus.dart';
part 'SearchProdi.dart';
part 'detailbottomsheet.dart';
part 'detail_bottomSheetWebJurusan.dart';
part 'Prospek.dart';
part 'cekbiaya.dart';
part 'daftar_registrasi.dart';
part 'CardProspek.dart';
part 'daftar_kuliah.dart';
part 'invoice.dart';
part 'invoice_struk.dart';
part 'SearchProdiHasil.dart';
part 'listProdi.dart';
part 'caraPembayaran.dart';
part 'berita_detail.dart';
part 'berita_tab.dart';
part 'detail_metodepembayaran.dart';
part 'SearchKampusHasil.dart';
part 'SearchCampusJurusan.dart';
part 'daftar_nonregistrasi.dart';
part 'list_promo.dart';
part 'cekbiayaWebJurusan.dart';
part 'daftar_kuliahWebJurusan.dart';
